services:
    friendly.type.guesser.array_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\ArrayGuesser
        arguments:
            - @friendly.type.guesser_registry
            - @friendly.utils.text_formater
        tags:
            - { name: friendly.type.guesser, priority: 100 }

    friendly.type.guesser.bigint_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\BigintGuesser
        arguments:
            - @friendly.type.guesser.int_guesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.boolean_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\BooleanGuesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.collection_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\CollectionGuesser
        arguments:
            - @friendly.type.guesser.array_guesser
        tags:
            - { name: friendly.type.guesser, priority: 100 }

    friendly.type.guesser.datetime_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\DatetimeGuesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.decimal_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\DecimalGuesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.entity_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\EntityGuesser
        arguments:
            - @friendly.record.collection.bag
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.int_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\IntGuesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.smallint_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\SmallintGuesser
        arguments:
            - @friendly.type.guesser.int_guesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser.string_guesser:
        class: Knp\FriendlyExtension\Type\Guesser\StringGuesser
        tags:
            - { name: friendly.type.guesser }

    friendly.type.guesser_registry:
        class: Knp\FriendlyExtension\Type\GuesserRegistry

